dwl_csuite:
  robot:
    init_position: [0., 0., 0.]
    init_rpy: [0., 0., 3.1416]
#    root_path:
    urdf_path: hyl/hyl.urdf
    yarf_path: hyl/hyl.yarf
  simulation:
    gui: true
    time_step: 1e-3
    gravity: [0., 0., -9.81]
    camera:
      distance: 1.5
      yaw: 16.
      pitch: -20.
      target: [0.2, 0., 0.15]
  control:
    default: csuite_PDController
    config_file: config/hyl.yaml
  ros:
    enable: false
    publish_rate: 100.